sandwalker/routes.py
"""Sandwalker routes."""

import csv
import datetime

from flask import Blueprint
from flask import abort, current_app, flash, jsonify, make_response, redirect, render_template, request, send_from_directory, url_for
from flask_minify import minify
from io import StringIO
from sassutils.wsgi import SassMiddleware
from sqlalchemy import and_, distinct, func, tuple_

from .models import db, TimelineEntry
from .forms import ReportForm, ViewPocketAccountHistoryForm
from .pocket import make_entries_by_month


sandwalker = Blueprint(
    'sandwalker', __name__, template_folder='templates',
    static_folder='static', static_url_path='/static/'
)


def last_height():
    entry = TimelineEntry.query.order_by(TimelineEntry.id.desc()).limit(1).first()

    return entry.block if entry else None

    return height


@sandwalker.route('/', methods=['GET', 'POST'])
def home():
    last = last_height()
    current_height = last if last else 'unknown'

    return render_template('home.html', current_height=current_height)


@sandwalker.route('/sandwalker-daily-dump.tar.gz', methods=['GET'])
def dump():
    return send_from_directory('/data', 'timeline-backup.db.tar.gz', as_attachment=True)


@sandwalker.route('/explorer', methods=['GET', 'POST'])
def explorer(account=None):

    # Redirect to the nice URL /explorer/<account>/
    form = ViewPocketAccountHistoryForm()
    if request.method == 'POST' and form.validate_on_submit():
        return redirect(url_for('sandwalker.explore', account=form.account.data))

    return render_template('explorer.html', form=form)


def sanitize_accounts(accounts):
    splitters = [',', '\r', '\n', '\t', ';']
    for splitter in splitters:
        accounts = accounts.replace(splitter, ' ')
    result = []

    for account in accounts.split(' '):
        clean_account = account.lower().strip()
        if clean_account:
            result.append(clean_account)

    return result


@sandwalker.route('/reporter', methods=['GET', 'POST'])
def reporter():
    form = ReportForm(request.form) if request.method == 'POST' else ReportForm(request.args)
    accounts = None
    entries = None
    node_count = 0

    # This can come both from GET or POST, directly use it without
    # checking if the form is valid.
    accounts = sanitize_accounts(form.accounts.data)

    if len(accounts) == 0:
        if request.method == 'POST':
            flash('Invalid list of account identifiers (accepted format: csv, space separated, tab separated, ...)', 'error')
    else:
        query = db.session.query(
            func.strftime("%Y-%m-01", TimelineEntry.time),
            func.sum(TimelineEntry.amount)).filter(
                TimelineEntry.account.in_(accounts)).group_by(
                    func.strftime("%Y-%m-01", TimelineEntry.time))

        entries = query.all()
        node_count = len(accounts)

    return render_template('reporter.html', form=form, accounts=accounts, entries=entries, node_count=node_count)


@sandwalker.route('/csv/overview', methods=['POST'])
def export_csv_overview():
    form = ReportForm()

    fields = ['month', 'account', 'total_upkt']
    output = StringIO()
    csv_writer = csv.DictWriter(output, fieldnames=fields)
    csv_writer.writeheader()

    if form.validate_on_submit():
        accounts = sanitize_accounts(form.accounts.data)
        query = db.session.query(
            func.strftime("%Y-%m-01", TimelineEntry.time),
            TimelineEntry.account,
            func.sum(TimelineEntry.amount)).filter(
                TimelineEntry.account.in_(accounts)).group_by(
                    func.strftime("%Y-%m-01", TimelineEntry.time),
                    TimelineEntry.account)

        entries = query.all()

        for entry in entries:
            csv_writer.writerow(
                {'month': entry[0], 'account': entry[1], 'total_upkt': float(entry[2])})

    response = make_response(output.getvalue())
    response.headers["Content-Disposition"] = 'attachment; filename=pocket_monthly_report.csv'
    response.headers["Content-type"] = 'text/csv'

    return response


@sandwalker.route('/explore/<account>', methods=['GET'])
def explore(account):

    entries_by_month = []
    total = None
    count = None

    if account:
        account = account.lower().strip()
        entries = TimelineEntry.query.filter(TimelineEntry.account == account).all()

        if len(entries) == 0:
            flash('No reward were found for {0}'.format(account), 'error')

        count, total, entries_by_month = make_entries_by_month(entries)
    
    return render_template(
        'explore.html', account=account, entries_by_month=entries_by_month, total=total, count=count)


@sandwalker.route('/csv/account/<account>', methods=['GET'])
def export_csv_account(account):
    fields = ['block_time', 'block_height', 'reward_upkt']
    output = StringIO()
    csv_writer = csv.DictWriter(output, fieldnames=fields)
    csv_writer.writeheader()

    account = account.lower()
    entries = TimelineEntry.query.filter(TimelineEntry.account == account).all()
    for entry in entries:
        csv_writer.writerow(
            {'block_time': entry.time, 'block_height': entry.block, 'reward_upkt': entry.amount})

    response = make_response(output.getvalue())
    response.headers["Content-Disposition"] = 'attachment; filename={0}.csv'.format(account)
    response.headers["Content-type"] = 'text/csv'

    return response


@sandwalker.route('/about')
def about():
    return render_template('about.html')


@sandwalker.route('/resources', methods=['GET'])
def resources():
    return render_template('resources.html')


@sandwalker.route('/api/height', methods=['GET', 'POST'])
def api_height():
    height = last_height()
    if not height:
        return jsonify({'error': 'Sandwalker has not initialized yet and has no complete block synced'}), 503

    # We return the height -1 here to handle consistency properly: if
    # we are process rewards of the current block, it will yield
    # incomplete data for this block. The previous block is 100% OK
    # though.

    result = {'height': height - 1}
    return jsonify(result), 200


@sandwalker.route('/api/block', methods=['GET', 'POST'])
def api_block():
    req = request.json

    if 'block' not in req:
        return jsonify({'error': 'Invalid request: no block specified'}), 400
    block = req.get('block')

    result = {'entries': []}
    entries = TimelineEntry.query.filter(
        TimelineEntry.block == block).all()

    for entry in entries:
        result['entries'].append({
            'reward': entry.amount,
            'account': entry.account,
            'time': entry.time,
        })

    return jsonify(result), 200


@sandwalker.route('/api/rewards', methods=['GET', 'POST'])
def api_rewards():
    req = request.json

    if 'accounts' not in req:
        return jsonify({'error': 'Invalid request: no Pocket accounts specified'}), 400
    accounts = [a.lower().strip() for a in req['accounts']]

    start_date = req.get('start_date', '1970-01-01 00:00:00')
    end_date = req.get('end_date', datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S'))

    result = {'accounts': {}}

    for account in accounts:
        result['accounts'][account] = list()
        entries = TimelineEntry.query.filter(
            and_(
                TimelineEntry.account == account,
                TimelineEntry.time.between(start_date, end_date))).all()

        for entry in entries:
            result['accounts'][account].append({
                'reward': entry.amount,
                'block': entry.block,
                'time': entry.time,
            })

    return jsonify(result), 200


@sandwalker.app_errorhandler(404)
def page_not_found(e):
    return render_template('error.html', error='The page you requested was not found'), 404


@sandwalker.app_errorhandler(500)
def page_crashed(e):
    return render_template('error.html', error='Some mysterious internal error occurred'), 500


def init_app(app):
    # Custom JINJA2 filters
    @app.template_filter()
    def filter_errors(form_errors):
        errs = set()
        for key, values in form_errors.items():
            for err in values:
                errs.add(err)
        return list(errs)
    app.jinja_env.filters['filter_errors'] = filter_errors

    # CSS/JS minimify and SASS compile.
    minify(
        app=app, html=True, js=True, cssless=True,
        script_types=['text/javascript'], bypass=['.*\\.min\\.js'])

    app.wsgi_app = SassMiddleware(app.wsgi_app, {
        'sandwalker': ('static/sass', 'static/css', '/static/css')
    })

sandwalker/templates/_flashes.html
{% with errors = get_flashed_messages(category_filter=["error"]) %}

{% if errors %}
{% for error in errors %}
<p class="flash-ko">
  <span class="flash-icon-ko">{{ error|safe }}</span>
</p>
{% endfor %}
{% endif %}

{% endwith %}

{% with successes = get_flashed_messages(category_filter=["success"]) %}

{% if successes %}
{% for success in successes %}
<p class="flash-ok">
  <span class="flash-icon-ok">{{ success|safe }}</span>
</p>
{% endfor %}
{% endif %}

{% endwith %}

sandwalker/templates/_macros.html
{% macro render_errors(form) %}
{% if form.errors %}

{% for error in form.errors | filter_errors %}
<p class="flash-ko">
  <span class="flash-icon-ko">{{ error }}</span>
</p>
{% endfor %}

{% endif %}
{% endmacro %}

{% macro render_field(field, label=None, label_visible=true, right_url=None, right_label=None) -%}
<div class="{% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
  {% if field.type != 'HiddenField' and label_visible %}
  {% if not label %}{% set label=field.label.text %}{% endif %}
  <label for="{{ field.id }}">{{ label|safe }}{% if field.errors %} <span class="error-star"><b>*</b></span>{% endif %}</label>
  {% endif %}
  {{ field(class_='form-control', **kwargs) }}
</div>
{%- endmacro %}

sandwalker/templates/about.html
{% extends "base.html" %}

{% set active = "about" %}

{% block content %}
<article lang="en">
  <header>
    <h1>Sand Walker</h1>

    {% include "glfx.html" %}

    <small>The Pocket Reward Explorer</small>
  </header>
  <div id="content">
    {% include "_flashes.html" %}

    <h3>About the Sand Walker</h3>
    
    <p>
      The Sand Walker project is an open-source real-time Pocket
      reward explorer, more information about the the project can be
      found
      in <a href="https://forum.pokt.network/t/pep-7-the-sand-walker-a-pocket-reward-explorer/977/">PEP-7</a>
      and in
      its <a href="https://github.com/skillz-blockchain/sandwalker">repository</a>.
    </p>

  </div>
</article>
{% endblock %}

sandwalker/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
    <meta name="description" content="Pocket Reward Explorer">
 
    <link href="{{ url_for('static', filename='css/_reset.scss.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.scss.css') }}" rel="stylesheet">

    <title>The Sand Walker -- Pocket Reward Explorer</title>

  </head>
  <body>

    <nav>
      <ul>
	<li class='{% if active == "home" %} active {% endif %}'>
	  <a href="{{ url_for('sandwalker.home') }}">Home</a>
	</li>
	<li class='{% if active == "explorer" %} active {% endif %}'>
	  <a href="{{ url_for('sandwalker.explorer') }}">Explorer</a>
	</li>
	<li class='{% if active == "reporter" %} active {% endif %}'>
	  <a href="{{ url_for('sandwalker.reporter') }}">Reporter</a>
	</li>
	<li class='{% if active == "resources" %} active {% endif %}'>
	  <a href="{{ url_for('sandwalker.resources') }}">Resources</a>
	</li>
	<li class='{% if active == "about" %} active {% endif %}'>
	  <a href="{{ url_for('sandwalker.about') }}">About</a>
	</li>

	<div class="clear"></div>
      </ul>
    </nav>

    {% block content %}
    {% endblock %}

    <footer>
      <ul>
	<li>The <a href="{{ url_for('sandwalker.home') }}">Sand Walker</a> project by <a href="https://skillz.io/">SkillZ</a>.</li>
      </ul>
    </footer>

    <script type="text/javascript" src="{{ url_for('static', filename='js/lightense.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/glfx.js') }}"></script>
    
  </body>
</html>

sandwalker/templates/error.html
{% extends "base.html" %}

{% set active = "home" %}

{% block content %}
<article lang="en">
  <header>
    <h1>Sand Walker</h1>

    {% include "glfx.html" %}
    
    <small>Pocket Reward Explorer</small>
  </header>
  <div id="content">

    {% include "_flashes.html" %}

    <h3>A Wild Error Appears</h3>
    
    <p>
      {{ error }}
    </p>

  </div>
</article>
{% endblock %}

sandwalker/templates/explore.html
{% from "_macros.html" import render_field, render_errors %}

{% extends "base.html" %}

{% set active = "explorer" %}

{% block content %}
<article lang="en">
  <header>
    <h1>Sand Walker</h1>
    
    {% include "glfx.html" %}
    
    <small>The Pocket Reward Explorer</small>
  </header>
  <div id="content">

    {% include "_flashes.html" %}

    {% if entries_by_month %}

    <h3>Summary</h3>

    <ul>
      <li>{{ account }}</li>
      <li>{{ count }} rewards earned</li>
      <li>{{ '%0.3f'|format(total / 10**6) }} <small class="exp">pokt</small> minted</li>
    </ul>

    <a href="{{ url_for('sandwalker.export_csv_account', account=account) }}" class="right-button">Download CSV</a>
    <div class="clear"></div>
    
    <h3>History</h3>

    <ul>
      {% for month, month_entry in entries_by_month.items() %}
      <li><a href="#{{ month }}">{{ month }}</a> &mdash; {{ '%0.3f'|format(month_entry.month_total / 10**6) }} <small class="exp">pokt</small></li>
      {% endfor %}
    </ul>

    <h3>Full History</h3>

    {% for month, month_entry in entries_by_month.items() %}

    <h2 id="{{ month }}">
      <a href="#{{ month }}" class="large-button">
	Month {{ month }} &mdash; {{ '%0.3f'|format(month_entry.month_total / 10**6) }} <small class="exp">pokt</small>
      </a>
    </h2>

    <br />

    <div class="table-wrapper">
      <table>
        <thead>
          <tr>
	    <th>Id</th>
	    <th>Block Height</th>
	    <th>Block Time</th>
	    <th>Reward</th>
	    <th>Month Total</th>
	    <th>Total</th>
	  </tr>
	</thead>
	<tbody>
	  {% for entry in month_entry.entries %}
	  <tr>
	    <td>{{ entry.current_count }}</td>
	    <td>{{ entry.block }}</td>
	    <td>{{ entry.time }}</td>
	    <td>{{ '%0.3f'|format(entry.amount / 10**6) }} <small class="exp">pokt</small></td>
	    <td>{{ '%0.3f'|format(entry.current_month_total / 10**6) }} <small class="exp">pokt</small></td>
	    <td>{{ '%0.3f'|format(entry.current_total / 10**6) }} <small class="exp">pokt</small></td>
	  </tr>
	  {% endfor %}
	</tbody>
      </table>
    </div>

    {% endfor %}

    {% else %}

    <p>No reward for this account.</p>

    {% endif %}

  </div>

</article>
{% endblock %}

sandwalker/templates/explorer.html
{% from "_macros.html" import render_field, render_errors %}

{% extends "base.html" %}

{% set active = "explorer" %}

{% block content %}
<article lang="en">
  <header>
    <h1>Sand Walker</h1>
    
    {% include "glfx.html" %}
    
    <small>The Pocket Reward Explorer</small>
  </header>
  <div id="content">

    {% include "_flashes.html" %}
    {{ render_errors(form) }}

    <h3>Reward History Explorer</h3>

    <form action="" method="POST" novalidate formnovalidate class="form" role="form">
      {{ form.hidden_tag() }}
      
      {{ render_field(form.account, label='Pocket Account Identifier') }}
      
      <br />
      
      <input type="submit" value="View Rewards" />
      <div class="clear"></div>
      
    </form>

  </div>

</article>
{% endblock %}

sandwalker/templates/glfx.html
<canvas id="glfx"></canvas> 

<script id="glfx-vertex" type="x-shader/x-vertex">
  attribute vec3 position;
 
  void main() {
      gl_Position = vec4(position, 1.0);
  }
</script>

<script id="glfx-fragment" type="x-shader/x-fragment">
  {% include 'glfx.c' %}
</script>

sandwalker/templates/home.html
{% from "_macros.html" import render_field, render_errors %}

{% extends "base.html" %}

{% set active = "home" %}

{% block content %}
<article lang="en">
  <header>
    <h1>Sand Walker</h1>
    
    {% include "glfx.html" %}
    
    <small>The Pocket Reward Explorer</small>
  </header>
  <div id="content">

    {% include "_flashes.html" %}

    <h3>Current Height is <b>{{ current_height  }}</b></h3>

    <p>
      The <a href="{{ url_for('sandwalker.home') }}">Sandwalker
      Project</a> is reward explorer for
      the <a href="https://pokt.network/">Pocket Network project</a>.
      It provides a frontend to explore rewards of any Pocket account
      using live data.
    </p>

    <p>
      <a href="{{ url_for('sandwalker.explorer') }}" class="right-button">Start Exploring</a>
    </p>

  </div>
</article>
{% endblock %}

sandwalker/templates/overview.html
{% from "_macros.html" import render_field, render_errors %}

{% extends "base.html" %}

{% set active = "explorer" %}

{% block content %}
<article lang="en">
  <header>
    <h1>Sand Walker</h1>
    
    {% include "glfx.html" %}
    
    <small>The Pocket Reward Explorer</small>
  </header>
  <div id="content">

    {% include "_flashes.html" %}
    {{ render_errors(form) }}

    <h3>Reward History Explorer</h3>

    <form action="" method="POST" novalidate formnovalidate class="form" role="form">
      {{ form.hidden_tag() }}
      
      {{ render_field(form.account, label='Pocket Account Identifier') }}
      
      <br />
      
      <input type="submit" value="View Rewards" />
      <div class="clear"></div>
      
    </form>

  </div>

</article>
{% endblock %}

sandwalker/templates/reporter.html
{% from "_macros.html" import render_field, render_errors %}

{% extends "base.html" %}

{% set active = "reporter" %}

{% block content %}
<article lang="en">
  <header>
    <h1>Sand Walker</h1>
    
    {% include "glfx.html" %}
    
    <small>The Pocket Reward Explorer</small>
  </header>
  <div id="content">

    {% include "_flashes.html" %}
    {{ render_errors(form) }}

    {% if accounts %}

    <h3>Summary of Pocket Accounts (<small>{{ node_count }}</small>)</h3>

    {% if entries %}
    
    <div class="table-wrapper">
      <table>
        <thead>
          <tr>
	    <th>Month</th>
	    <th>Rewards</th>
	  </tr>
	</thead>
	<tbody>
	  {% for date, total in entries %}
	  <tr>
	    <td>{{ date }}</td>
	    <td>{{ '%0.3f'|format(total / 10**6) }} <small class="exp">pokt</small></td>
	  </tr>
	  {% endfor %}
	</tbody>
      </table>
    </div>

    <br />

    {% else %}

    <p>
      No rewards found for these nodes.
    </p>

    {% endif %}

    <a href="{{ url_for('sandwalker.reporter', accounts=accounts|join(' ')) }}" class="right-button">Direct Link</a>
    <form name="export_csv_overview" method="POST" action="{{ url_for('sandwalker.export_csv_overview') }}">
      <input type="hidden" name="accounts" value="{{ accounts|join(' ') }}">
      <input type="submit" class="right-button" value="Download CSV" />
    </form>
    <div class="clear"></div>

    <h3>Pocket Account Details</h3>

    <ul>
    {% for account in accounts %}
      <li><a href="{{ url_for('sandwalker.explore', account=account) }}">{{ account }}</a></li>
    {% endfor %}
    </ul>

    {% else %}
    <h3>Reward Report</h3>

    <form action="" method="POST" novalidate formnovalidate class="form" role="form">
      {{ form.hidden_tag() }}
      
      {{ render_field(form.accounts, label='List of Pocket Account Identifiers') }}

      <br />
      
      <input type="submit" value="Generate Report" />
      <div class="clear"></div>
      
    </form>
    {% endif %}

  </div>

</article>
{% endblock %}

sandwalker/templates/resources.html
{% extends "base.html" %}

{% set active = "resources" %}

{% block content %}
<article lang="en">
  <header>
    <h1>Sand Walker</h1>

    {% include "glfx.html" %}

    <small>The Pocket Reward Explorer</small>
  </header>
  <div id="content">
    {% include "_flashes.html" %}

    <h3>The Sandwalker Database</h3>

    <p>
      The database of the the Sand Walker project contains rewards entries
      from all pocket accounts since block 0, it is structured as follows:

      <ul>
	<li><b>id</b>, a unique internal identifier for the reward,</li>
	<li><b>account</b>, a pocket account,</li>
	<li><b>block</b>, the block height,</li>
	<li><b>reward</b>, the reward in <span class="exp">&#xB5;Pkt</span>.</li>
      </ul>

      <br />
      
      The database can be either rebuilt by replaying the blockchain
      using tools from
      the <a href="https://github.com/skillz-blockchain/sandwalker">public
      repository</a>, or by downloading it below.
    </p>

    <p>
      <a href="{{ url_for('sandwalker.dump') }}" class="right-button">Download Daily Dump</a>
    </p>

  </div>
</article>
{% endblock %}